name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"

  workflow_dispatch:

jobs:
  test:
    name: Backend Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Run tests
        working-directory: starter/backend
        run: pipenv run test

      - name: Run lint
        working-directory: starter/backend
        run: pipenv run lint

  build:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: starter/backend
        run: |
          docker build \
            --tag backend:${{ github.sha }} \
            .

      - name: Save Docker image
        run: |
          docker save backend:${{ github.sha }} -o backend.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend.tar